name = "cccccccclick"
compatibility_date = "2025-09-15"
main = "src/server/main.mts"
workers_dev = true

[assets]
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Counter"]
