name = "cccccccclick"
compatibility_date = "2025-09-15"
main = "src/server.ts"
workers_dev = false

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Counter"]
